name: dart_cryto_console
description: Console application that allows you to encrypt and decrypt texts in a simple way.
version: 3.5.20240827
homepage: https://tglima.github.io/

environment:
  sdk: '>=3.5.1 <3.5.9'

publish_to: none
dependencies:
    args: 2.5.0
    tglima_dart_framework: 
        git:
            url: https://github.com/tglima/Dart-Framework
            ref: main
            version: ^3.5.20240827

dev_dependencies:
  lints: 4.0.0
  test: ^1.16.0
